# Describes parameters for the "comms" system, which manages communications between
# the server and the agents
[Comms]
User = guest                       # Username for comms
Password = guest                   # Password for comms
Host = rabbitmq                   # Hostname or IP address for comms
Port = 5672                        # Port for comms
Plugin = rabbitmq                  # Comms plugin to use (i.e. "rabbitmq")

# Describes parameters for local resources, such as network or filesystem resources
[LocalResources]
DefaultInterface = eth0            # Dictates what network interface is used for testing
                                   # purposes (i.e. informs the todd-server which IP
                                   # address can be used

# IPAddrOverride = 192.168.99.100    # Overrides DefaultInterface by providing a specific IP
                                   # address rather

OptDir = /opt/todd/agent           # Operational directory for the agent. Houses things like
                                   # cache files, user-defined testlets, etc.
